name: bioinfosoft
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - jupyterlab=3
    - numpy
    - scipy
    - pandas
    - matplotlib
    - requests
    - lxml
    - biopython
    - xmltodict
    - dash
    - plotly
    # download data files
    - tqdm
    # linters and more
    - pylint
    - pycodestyle
    - pydocstyle
    - black
    - ruff